import "@/app/globals.css";
import PassDataProvider from "@/providers/PassedData";
import Navbar from "@/components/Navbar/Navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Herbalism - About',
  description: 'Generated by create next app',
  applicationName: 'Herbalism - Home',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'khoadev',
  authors: [{ name: 'khoadev' }],
  creator: 'khoadev'
}

const RootStructure = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <PassDataProvider>
        <section className="flex h-full w-full">
          {children}
        </section>
      </PassDataProvider >
    </>
  );
};

export default RootStructure;
