import { type Metadata } from 'next'
import './globals.css'
import Navbar from '@/layout/Navbar/Navbar';
import Footer from '@/layout/Footer/Footer';
import { useLanguage } from '@/hooks/useLanguage';
import ClientOnly from '@/components/ClientOnly/ClientOnly';
import { Suspense } from 'react';
import FontWrapper from './Providers/fontWrapper';
import { NotificationProvider } from './Providers/Notification';

export const metadata: Metadata = {
  title: 'Herbalism - Home',
  description: 'Generated by create next app',
  applicationName: 'Herbalism - Home',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'khoadev',
  authors: [{ name: 'khoadev' }],
  creator: 'khoadev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="vi">
      <head>
        <meta name="color-scheme" content="light only" />
      </head>
      <body className="min-h-screen flex flex-col">
        <ClientOnly>
          <NotificationProvider>
            <FontWrapper>
              <Suspense >{children}</Suspense>
            </FontWrapper>
          </NotificationProvider>
        </ClientOnly>
      </body>
    </html>
  )
}
