import "@/app/globals.css";
import Navbar from "@/layout/Navbar/Navbar";
import { Metadata } from "next";
import Footer from "@/layout/Footer/Footer";

export const metadata: Metadata = {
  title: 'Herbalism - Shop',
  description: 'Generated by create next app',
  applicationName: 'Herbalism - Home',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" }
  ],
  generator: 'khoadev',
  authors: [{ name: 'khoadev' }],
  creator: 'khoadev'
}

const RootStructure = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Navbar />
        {children}
      <Footer />
    </>
  );
};

export default RootStructure;
